ktor:
    deployment:
        port: 8080
    application:
        modules:
            - pl.szymanski.wiktor.ta.infrastructure.ApplicationKt.application
            - pl.szymanski.wiktor.ta.infrastructure.scheduler.SchedulerModuleKt.scheduler
            - pl.szymanski.wiktor.ta.infrastructure.scheduler.OfferSchedulerModuleKt.offerScheduler

database:
    uri: "mongodb://localhost:27017"
    dbName: "travel_agency"

offerScheduler:
  intervalSeconds: 10

scheduler:
    intervalSeconds: 1
    inAdvanceSeconds: 5
    creationWindowSeconds: 5
    accommodations:
        - name: "Hotel"
          location: "London"
        - name: "Hostel"
          location: "Berlin"
    attractions:
        - name: "Big Ben tour"
          location: "London"
          capacity: 10
        - name: "City tour by boat"
          location: "Berlin"
          capacity: 30
    commutes:
        - name: "London to Paris"
          departureLocation: "Paris"
          arrivalLocation: "London"
          seats:
              - row: "1"
                column: "A"
              - row: "2"
                column: "A"
        - name: "Paris to Berlin"
          departureLocation: "Paris"
          arrivalLocation: "Berlin"
          seats:
              - row: "3"
                column: "B"
              - row: "4"
                column: "B"
