ktor:
  deployment:
    port: 8080
  application:
    modules:
      - pl.szymanski.wiktor.ta.infrastructure.SchedulerKt.scheduler

database:
  uri: "mongodb://root:password@localhost:27017"
  dbName: "travel_agency"
#
#offerScheduler:
#  intervalSeconds: 0.5

generator:
  intervalSeconds: 1
  inAdvanceSeconds: 1000
  creationWindowSeconds: 10
  accommodations:
    # London Accommodations (15 total)
    - name: "Hotel"
      location: "London"
    - name: "Central Suites"
      location: "London"
    - name: "Royal Inn"
      location: "London"
    - name: "The London Retreat"
      location: "London"
    - name: "Cityscape Hotel"
      location: "London"
    - name: "The Crown Lodge"
      location: "London"
    - name: "Parkside Hotel"
      location: "London"
    - name: "Windsor Residence"
      location: "London"
    - name: "The Regent Hotel"
      location: "London"
    - name: "London Bridge Inn"
      location: "London"
    - name: "Thames View Hotel"
      location: "London"
    - name: "The Kensington"
      location: "London"
    - name: "City Lights Hostel"
      location: "London"
    - name: "Urban Stay"
      location: "London"
    - name: "Historical Inn"
      location: "London"

    # Berlin Accommodations (15 total)
    - name: "Hostel"
      location: "Berlin"
    - name: "Hotel B"
      location: "Berlin"
    - name: "Berlin Central Hotel"
      location: "Berlin"
    - name: "Alexanderplatz Inn"
      location: "Berlin"
    - name: "City Center Hostel"
      location: "Berlin"
    - name: "Spree River Hotel"
      location: "Berlin"
    - name: "Brandenburg Stay"
      location: "Berlin"
    - name: "Eastside Guesthouse"
      location: "Berlin"
    - name: "The Berlin Loft"
      location: "Berlin"
    - name: "Urban Vibes Hostel"
      location: "Berlin"
    - name: "The Wall Hotel"
      location: "Berlin"
    - name: "Checkpoint Charlie Inn"
      location: "Berlin"
    - name: "Cityscape Hotel Berlin"
      location: "Berlin"
    - name: "Museum Quarter Hotel"
      location: "Berlin"
    - name: "Alexander Hostel"
      location: "Berlin"

    # Rome Accommodations (15 total)
    - name: "Grand Palace Hotel"
      location: "Rome"
    - name: "Roman Holiday Inn"
      location: "Rome"
    - name: "Colosseum View Hotel"
      location: "Rome"
    - name: "Vatican Suites"
      location: "Rome"
    - name: "Trevi Fountain Hotel"
      location: "Rome"
    - name: "Piazza Navona Inn"
      location: "Rome"
    - name: "The Eternal City Hotel"
      location: "Rome"
    - name: "Roman Forum Guesthouse"
      location: "Rome"
    - name: "Pantheon Residence"
      location: "Rome"
    - name: "City Center Hotel Rome"
      location: "Rome"
    - name: "Trastevere Inn"
      location: "Rome"
    - name: "Roman Nights Hostel"
      location: "Rome"
    - name: "Appian Way Hotel"
      location: "Rome"
    - name: "The Basilica Inn"
      location: "Rome"
    - name: "Historic Rome Hotel"
      location: "Rome"

    # Amsterdam Accommodations (15 total)
    - name: "Cozy Apartment"
      location: "Amsterdam"
    - name: "Canal View Hostel"
      location: "Amsterdam"
    - name: "City Center Hotel Amsterdam"
      location: "Amsterdam"
    - name: "Museum Quarter Inn"
      location: "Amsterdam"
    - name: "Dam Square Hotel"
      location: "Amsterdam"
    - name: "Old Town Guesthouse"
      location: "Amsterdam"
    - name: "The Tulip Hotel"
      location: "Amsterdam"
    - name: "Artis Zoo Hostel"
      location: "Amsterdam"
    - name: "Jordaan Suites"
      location: "Amsterdam"
    - name: "Bike Friendly Hostel"
      location: "Amsterdam"
    - name: "Historic Canal Hotel"
      location: "Amsterdam"
    - name: "The Windmill Inn"
      location: "Amsterdam"
    - name: "Urban Stay Amsterdam"
      location: "Amsterdam"
    - name: "The Linden Hotel"
      location: "Amsterdam"
    - name: "Central Station Inn"
      location: "Amsterdam"

    # Zermatt Accommodations (15 total)
    - name: "Mountain Cabin"
      location: "Zermatt"
    - name: "Alpine Lodge"
      location: "Zermatt"
    - name: "Ski Resort Hotel"
      location: "Zermatt"
    - name: "Matterhorn Inn"
      location: "Zermatt"
    - name: "The Chalet Hotel"
      location: "Zermatt"
    - name: "Snowpeak Hostel"
      location: "Zermatt"
    - name: "Peak View Lodge"
      location: "Zermatt"
    - name: "Glacier Hotel"
      location: "Zermatt"
    - name: "The Alpine Chalet"
      location: "Zermatt"
    - name: "Summit Inn"
      location: "Zermatt"
    - name: "Ski Trail Hostel"
      location: "Zermatt"
    - name: "The Mountain View Hotel"
      location: "Zermatt"
    - name: "Zermatt Central Hotel"
      location: "Zermatt"
    - name: "Woodland Cabin"
      location: "Zermatt"
    - name: "The Snowy Peak"
      location: "Zermatt"

    # Vienna Accommodations (15 total)
    - name: "City Center Inn"
      location: "Vienna"
    - name: "Opera House Hotel"
      location: "Vienna"
    - name: "Ringstrasse Suites"
      location: "Vienna"
    - name: "Historic Center Inn"
      location: "Vienna"
    - name: "Vienna Central Hostel"
      location: "Vienna"
    - name: "Prater Park Hotel"
      location: "Vienna"
    - name: "Museum District Lodge"
      location: "Vienna"
    - name: "Imperial Guesthouse"
      location: "Vienna"
    - name: "Danube View Hotel"
      location: "Vienna"
    - name: "Viennese Charm Inn"
      location: "Vienna"
    - name: "The Hofburg Hotel"
      location: "Vienna"
    - name: "City Lights Hotel"
      location: "Vienna"
    - name: "Historic Opera Suite"
      location: "Vienna"
    - name: "Urban Stay Vienna"
      location: "Vienna"
    - name: "Stephansplatz Hostel"
      location: "Vienna"

    # Barcelona Accommodations (15 total)
    - name: "Beachside Resort"
      location: "Barcelona"
    - name: "Gothic Quarter Hotel"
      location: "Barcelona"
    - name: "La Rambla Inn"
      location: "Barcelona"
    - name: "Beachfront Hostel"
      location: "Barcelona"
    - name: "Catalonia Suites"
      location: "Barcelona"
    - name: "Sagrada Familia Hotel"
      location: "Barcelona"
    - name: "Park Guell Inn"
      location: "Barcelona"
    - name: "City Center Hostel Barcelona"
      location: "Barcelona"
    - name: "The Mediterranean Hotel"
      location: "Barcelona"
    - name: "Barceloneta Lodge"
      location: "Barcelona"
    - name: "Urban Beach Hotel"
      location: "Barcelona"
    - name: "Eixample Suites"
      location: "Barcelona"
    - name: "The Picasso Inn"
      location: "Barcelona"
    - name: "Modernist Hostel"
      location: "Barcelona"
    - name: "Magic Fountain Hotel"
      location: "Barcelona"

    # Paris Accommodations (15 total)
    - name: "Boutique Hotel"
      location: "Paris"
    - name: "Eiffel Tower View Inn"
      location: "Paris"
    - name: "Montmartre Hostel"
      location: "Paris"
    - name: "Louvre Suites"
      location: "Paris"
    - name: "Saint-Germain Hotel"
      location: "Paris"
    - name: "Latin Quarter Inn"
      location: "Paris"
    - name: "Champs Elysees Hotel"
      location: "Paris"
    - name: "Opera District Hostel"
      location: "Paris"
    - name: "The Marais Guesthouse"
      location: "Paris"
    - name: "Seine Riverside Hotel"
      location: "Paris"
    - name: "City Center Hostel Paris"
      location: "Paris"
    - name: "Belleville Inn"
      location: "Paris"
    - name: "Historic Paris Hotel"
      location: "Paris"
    - name: "Urban Stay Paris"
      location: "Paris"
    - name: "Père Lachaise Guesthouse"
      location: "Paris"

  attractions:
    # London
    - name: "Big Ben tour"
      location: "London"
      capacity: 3
    - name: "Westminster Abbey Visit"
      location: "London"
      capacity: 3
    # Berlin
    - name: "City tour by boat"
      location: "Berlin"
      capacity: 3
    - name: "Berlin Wall Museum"
      location: "Berlin"
      capacity: 3
    # Rome
    - name: "Colosseum Visit"
      location: "Rome"
      capacity: 3
    - name: "Vatican Museums Tour"
      location: "Rome"
      capacity: 3
    # Amsterdam
    - name: "Canals Bike Tour"
      location: "Amsterdam"
      capacity: 3
    - name: "Rijksmuseum Visit"
      location: "Amsterdam"
      capacity: 3
    # Zermatt
    - name: "Alpine Hiking"
      location: "Zermatt"
      capacity: 3
    - name: "Matterhorn Cable Car Ride"
      location: "Zermatt"
      capacity: 3
    # Vienna
    - name: "Vienna Opera House"
      location: "Vienna"
      capacity: 3
    - name: "Schönbrunn Palace Visit"
      location: "Vienna"
      capacity: 3
    # Barcelona
    - name: "Barcelona Beach Festival"
      location: "Barcelona"
      capacity: 3
    - name: "Sagrada Familia Tour"
      location: "Barcelona"
      capacity: 3
    # Paris
    - name: "Eiffel Tower Visit"
      location: "Paris"
      capacity: 3
    - name: "Louvre Museum Tour"
      location: "Paris"
      capacity: 3

  commutes:
    # Poznan to London
    - name: "Poznan to London"
      departureLocation: "Poznan"
      arrivalLocation: "London"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Venice to Berlin
    - name: "Venice to Berlin"
      departureLocation: "Venice"
      arrivalLocation: "Berlin"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Zurich to Rome
    - name: "Zurich to Rome"
      departureLocation: "Zurich"
      arrivalLocation: "Rome"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Budapest to Amsterdam
    - name: "Budapest to Amsterdam"
      departureLocation: "Budapest"
      arrivalLocation: "Amsterdam"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Madrid to Zermatt
    - name: "Madrid to Zermatt"
      departureLocation: "Madrid"
      arrivalLocation: "Zermatt"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Lyon to Vienna
    - name: "Lyon to Vienna"
      departureLocation: "Lyon"
      arrivalLocation: "Vienna"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Valencia to Barcelona
    - name: "Valencia to Barcelona"
      departureLocation: "Valencia"
      arrivalLocation: "Barcelona"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"

    # Marseille to Paris
    - name: "Marseille to Paris"
      departureLocation: "Marseille"
      arrivalLocation: "Paris"
      seats:
        - row: "1"
          column: "A"
        - row: "1"
          column: "B"
        - row: "2"
          column: "A"
        - row: "2"
          column: "B"
        - row: "3"
          column: "A"
        - row: "3"
          column: "B"
        - row: "4"
          column: "A"
        - row: "4"
          column: "B"
        - row: "5"
          column: "A"
        - row: "5"
          column: "B"