version: '3.8'

services:
  mongodb_1:
    image: mongo:8.0
    container_name: mongodb_1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/mongo-keyfile" ]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_1:/data/db
      - ./mongo-keyfile:/data/mongo-keyfile:ro
    networks:
      - mongo-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: travel_agency

  mongodb_2:
    image: mongo:8.0
    container_name: mongodb_2
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/mongo-keyfile" ]
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_2:/data/db
      - ./mongo-keyfile:/data/mongo-keyfile:ro
    networks:
      - mongo-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: travel_agency

  mongoinit:
    image: mongo:8.0
    container_name: mongoinit
    depends_on:
      - mongodb_1
      - mongodb_2
    networks:
      - mongo-net
    restart: "no"
    volumes:
      - ./mongo-init.sh:/mongo-init.sh:ro
    entrypoint: [ "bash", "/mongo-init.sh" ]

  kurrentdb:
    image: kurrentplatform/kurrentdb:latest
    container_name: kurrentdb
    restart: unless-stopped
    environment:
      KURRENTDB_INSECURE: "true"
      KURRENTDB_RUN_PROJECTIONS: All
      KURRENTDB_START_STANDARD_PROJECTIONS: "true"
      KURRENTDB_NODE_IP: 0.0.0.0
      KURRENTDB_REPLICATION_IP: 0.0.0.0
      KURRENTDB_NODE_PORT: 2113
      KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS: 127.0.0.1
      KURRENTDB_DEFAULT_ADMIN_PASSWORD: "changeit"
    ports:
      - "2113:2113"
    volumes:
      - kurrentdb_data:/var/lib/kurrentdb
    networks:
      - mongo-net

networks:
  mongo-net:

volumes:
  mongodb_data_1:
    driver: local
  mongodb_data_2:
    driver: local
  kurrentdb_data:
    driver: local
