name: detekt.yml

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detekt:
    name: Check detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload SARIF to GitHub
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/report.sarif